manifest:
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zephyr
      repo-path: zephyr
      remote: zephyrproject
      import:
        path-prefix: deps
        name-allowlist:
          - cmsis_6
          - percepio
          - picolibc
          - mcuboot
          - trusted-firmware-m
          - segger
          - mbedtls
          - tf-psa-crypto
          - hal_espressif
          - hal_xtensa
      revision: v4.4.1
